# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_and_test

on:
# why use pull_request_target? https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action
  pull_request_target:
    branches: [ main, develop, release, feature/** ]

#https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for coming to my TED talk!'
            })
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run lint
    # - run: npm run build --if-present
    # - run: npm run test:coverage
    
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: doorway-v3-build
    #     path: docs/

    # - name: configure aws credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::466903752538:role/ccnp-doorway-client-role
    #     role-session-name: doorwayupload
    #     aws-region: us-east-1

    # - name: Delete existing site files
    #   run: |
    #     aws s3 rm s3://ccnp-doorway-client --recursive

    # - name: Copy build files to s3
    #   run: |
    #     aws s3 cp --recursive ./docs/ s3://ccnp-doorway-client/
